### PR TITLE
closing feature #6088

### PR DESCRIPTION
**Pull request by CecileBONIN**

### CODE REVIEW

**Comment by CecileBONIN** [comment]
Please don't forget to take in account the following associated PRs :

https://github.com/Silverpeas/Silverpeas-Components/pull/360

**Comment by SilverYoCha** [comment]
For now, integration can not be performed because of the failure of some unit tests:
- some of CommentUserNotificationServiceTest class
- some of UserNotificationBuilderTest class

Also, I have noticed the use of StringBuffer class instead of StringBuilder. Today, the rule is to use StringBuilder (For our use, the mechanism of StringBuffer is less powerful that the one of StringBuilder).

**Comment by CecileBONIN** [comment]
ok, I have resolved the problem of unit tests.
And I have used the StringBuilder instead of StringBuffer.

**Comment by SilverYoCha** [comment]
After getting the fixes, I still had failures on CommentUserNotificationServiceTest.
I fixed them by adding some missing bundle resources (it seems that is a different behavior of JVM between Windows and Linux environment around the access of resources that do not exist).

**Pull request merged**
