### PR TITLE
[Login] Feature #9464 - Default domain

### PR DESCRIPTION
**Pull request by NicolasEYSSERIC**

### CODE REVIEW

**Comment by mmoqui** [comment]
The anonymous mode doesn't work anymore with and without the loginPage.domainId.default parameter set.

**Comment by NicolasEYSSERIC** [comment]
I just fixed the issue with anonymous mode.

**Comment by mmoqui** [comment]
The issue with the anonymous mode is indeed fixed. Nevertheless, when enabled, the feature doesn't work: if both the anonymous mode and the default domain are enabled, the latter isn't taken into account when asking to sign in.

**Comment by NicolasEYSSERIC** [comment]
Miguel, I think you did not delete your cookie 'defaultDomain' before testing.
If you don't delete it, the feature doesn't work because it is not your first connection.

**Comment by mmoqui** [comment]
The PR was rebased before being merged.

**Pull request closed without merging**
