### PR TITLE
[Workflows] Fixing bugs 7236 and 8093

### PR DESCRIPTION
**Pull request by NicolasEYSSERIC**
Do not forget to check out corresponding PR on Silverpeas-Components...

### CODE REVIEW

**Comment by mmoqui** [comment]
In the header of a request of a vacation leave, when invoking the _print_ action, an error is thrown in the logs:
 [STDOUT] ERROR : form.EX_CANT_OPEN_FILE | MODULE : form.HtmlForm.toString | Impossible d'ouvrir le fichier (EXCEPTION : java.io.FileNotFoundException: DemandeCongesSimple/print.html (No such file or directory)

It appears the html file isn't found in the SILVERPEAS_DATA/workflowRepository/DemandeCongesSimple/ as expected, whereas the others view overrides are well found (the one for presentationForm for example)

**Comment by NicolasEYSSERIC** [comment]
It seems like you do not have checked out corresponding PR on Silverpeas-Components, no ?

**Comment by mmoqui** [comment]
yes effectively, I missed the PR in Silverpeas-Components. Sorry.

**Comment by mmoqui** [comment]
Merged. Don't detected by Github because the branch was synchronized with core-5.15.x by rebase.

**Pull request closed without merging**
